version: '3'

services:
  api:
    image: dayonel/neverminder
    container_name: neverminder-api
    expose:
      - "5000"
    networks:
      - bridge_network
    volumes:
      - db-data:/var/lib/sqlite

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - bridge_network
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: ${CERTBOT_COMMAND}

networks:
  bridge_network:
    driver: bridge

volumes:
  db-data: