services:
  api:
    image: dayonel/neverminder
    container_name: neverminder-api
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge_network

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-name
      POSTGRES_USER: db-username
      POSTGRES_PASSWORD: db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bridge_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db-name -U db-username"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  bridge_network:
    driver: bridge

volumes:
  db-data: